"""remove etiqueta_ok from checklist_recebimento

Revision ID: 3b6761b3b9e3
Revises: add_remessa_field_20260317
Create Date: 2026-03-24 16:09:52.695110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6761b3b9e3'
down_revision = 'add_remessa_field_20260317'
branch_labels = None
depends_on = None


def upgrade():
    # Remove apenas a coluna etiqueta_ok da tabela checklist_recebimento
    with op.batch_alter_table('checklist_recebimento', schema=None) as batch_op:
        batch_op.drop_column('etiqueta_ok')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wms_reconciliacao_divergencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wms_reconciliacao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wms_reconciliacao_nota'), ['numero_nota'], unique=False)

    with op.batch_alter_table('wms_integracao_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wms_integracao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wms_integracao_referencia'), ['referencia'], unique=False)

    with op.batch_alter_table('wms_alerta_operacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wms_alerta_status'), ['status'], unique=False)

    with op.batch_alter_table('permissao_acesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_permissao_scope_key'), ['scope_type', 'scope_id', 'permission_key'], unique=1)

    with op.batch_alter_table('localizacao_armazem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_localizacao_armazem_rua'))
        batch_op.drop_index(batch_op.f('ix_localizacao_armazem_predio'))
        batch_op.drop_index(batch_op.f('ix_localizacao_armazem_nivel'))
        batch_op.drop_index(batch_op.f('ix_localizacao_armazem_apartamento'))
        batch_op.alter_column('codigo',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('item_wms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_wms_ordem_servico'))
        batch_op.drop_index(batch_op.f('ix_item_wms_ordem_compra'))
        batch_op.drop_index(batch_op.f('ix_item_wms_codigo_grv'))

    with op.batch_alter_table('item_nota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_nota_tipo_documento'))
        batch_op.drop_index(batch_op.f('ix_item_nota_sem_conferencia_logistica'))
        batch_op.drop_index(batch_op.f('ix_item_nota_remessa'))
        batch_op.drop_index(batch_op.f('ix_item_nota_pedido_compra'))
        batch_op.drop_index(batch_op.f('ix_item_nota_pagamento_xml'))
        batch_op.drop_index(batch_op.f('ix_item_nota_ncm'))
        batch_op.drop_index(batch_op.f('ix_item_nota_material_cliente'))
        batch_op.drop_index(batch_op.f('ix_item_nota_documento_externo_id'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cst_pis'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cst_icms'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cst_cofins'))
        batch_op.drop_index(batch_op.f('ix_item_nota_codigo_verificacao'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cnpj_emitente'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cnpj_destinatario'))
        batch_op.drop_index(batch_op.f('ix_item_nota_cfop'))
        batch_op.drop_index(batch_op.f('ix_item_nota_auditor_status'))
        batch_op.drop_index(batch_op.f('ix_item_nota_auditor_decisao'))

    with op.batch_alter_table('checklist_recebimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiqueta_ok', sa.BOOLEAN(), nullable=False))

    op.create_table('etiqueta_recebimento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero_nota', sa.VARCHAR(length=20), nullable=False),
    sa.Column('usuario_impressao', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data_impressao', sa.DATETIME(), nullable=False),
    sa.Column('quantidade_impressao', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etiqueta_recebimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etiqueta_recebimento_numero_nota'), ['numero_nota'], unique=1)

    # ### end Alembic commands ###
