"""initial modular schema

Revision ID: 95019c662378
Revises: 
Create Date: 2026-03-09 15:47:10.763941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95019c662378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_nota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_nota_numero_nota'), ['numero_nota'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_nota_status'), ['status'], unique=False)

    with op.batch_alter_table('log_divergencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_divergencia_numero_nota'), ['numero_nota'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))

    with op.batch_alter_table('log_divergencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_divergencia_numero_nota'))

    with op.batch_alter_table('item_nota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_nota_status'))
        batch_op.drop_index(batch_op.f('ix_item_nota_numero_nota'))

    # ### end Alembic commands ###
